spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wws12345
    url: jdbc:mysql://127.0.0.1:3306/cs?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
      initial-size: 2
      min-idle: 2
      max-wait: 60000
      filters: stat

# application.yml
mybatis:
    type-aliases-package: com.database.cs.entity
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 3000
    mapper-locations: classpath:mappers/*.xml
server:
  servlet:
    context-path: /cs
  port: 8080
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#logging:
#  path: /Users/wang/temp/log/cs.log
#  level: info