spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wws123
    url: jdbc:mysql://127.0.0.1:3306/cs?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      initial-size: 10
      min-idle: 20
      max-wait: 60000
      filters: stat
  redis:
    host: 127.0.0.1
    password: a123456
    port: 6379
    jedis:
      pool:
        max-idle: 700
        min-idle: 500
        max-active: 1000
    timeout: 10s
# application.yml
mybatis:
    type-aliases-package: com.database.cs.entity
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 3000
    mapper-locations: classpath:mappers/*.xml
server:
  servlet:
    context-path: /cs
  port: 8080
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#logging:
#  path: /Users/wang/temp/log/cs.log
#  level: info